### ISSUE TITLE
Doesn't proceed to the next step

### ISSUE THREAD

**Issue by docSoliday** [farfromunique/vampirePoints#40]
I filled in the text boxes and then selected a clan like I was instructed but was not moved to step 2.

I also received 2 warnings:

Warning: array_key_exists() expects parameter 2 to be array, null given in /home/public/classes/attribute.class.php on line 26

Warning: array_key_exists() expects parameter 2 to be array, null given in /home/public/classes/attribute.class.php on line 26

**Comment by farfromunique** [comment]
Thanks for the bug report! I have to dig back in to this to figure out what the issue is - I suspect it has to do with the database.

I'll probably wind up finishing a re-write on it as a fix. I've learned a lot of things since I last worked on this...

**Comment by farfromunique** [comment]
@docSoliday This is caused by a code mismatch. Next release will resolve it. Expect an update in ~2 weeks
